javascripts/discourse/connectors/above-site-header/category-header-widget.hbs
settings.yml

above_site_header or below_site_header, default is below_site_header

FEATURE: adds a setting to choose which connector to use

---

common/common.scss
javascripts/discourse/widgets/category-header-widget.js.es6
settings.yml

I've added a setting that enables attaching the widget from discourse-category-icons on the left of the banner title.
This is something I'll use on my community and I thought could be contributed back. I'm no expert on Discourse internals, though, so just let me know if anything can be improved.
Example:
EDIT: I'm using 1.5em as width/height for the icon, but having tested with 1.75em I think it's slightly better. If you're willing to accept this PR just let me know your preference.

Setting to show category icon from discourse-category-icons component

---

javascripts/discourse/widgets/category-header-widget.js.es6

This change ensures the banner will remain visible when filtering a category by a tag.

FEATURE: Support filtering by tag

---

javascripts/discourse/widgets/category-header-widget.js.es6

This change swaps out `Category.findById` with `Category.findBySlugPathWithID`. It ends up reducing the necessary code and handles the scenario of using a link without a numeric ID (e.g. `/tags/c/some-category/some-tag` instead of  `/tags/c/some-category/4/some-tag`).
This also simplifies the routing logic in line with what was discussed in https://github.com/discourse/discourse-category-banners/pull/8. There's no need to create an `isCategoryTopicList` variable, especially now that the code is a little less busy.

REFACTOR: Simplify routing logic and use Category.findBySlugPathWithID

---

common/common.scss
javascripts/discourse/widgets/category-header-widget.js.es6

This PR adjusts where the lock is placed in the widget. It will now more closely resemble the way Discourse shows lock icons inside of the title element for category titles. This will allow better customization of displaying the text and icon for users who wish to alter the style of the component.
```html
<h1 class="category-title">
<svg class="fa d-icon d-icon-lock svg-icon svg-node" aria-hidden="true">
<use xlink:href="#lock"></use>
</svg>
Staff
</h1>
```
```html
<svg class="fa d-icon d-icon-lock svg-icon svg-node" aria-hidden="true">
<use xlink:href="#lock"></use>
</svg>
<h1 class="category-title">Staff</h1>
```

DEV: Change lock placement

---

common/common.scss
javascripts/discourse/components/discourse-category-banners.hbs
javascripts/discourse/components/discourse-category-banners.js
settings.yml

This address some feedback from: https://meta.discourse.org/t/category-banners/86241/164?u=awesomerobot
It improves the alignment of the category icon when available and adds a setting to override its color. 
I've also added a check for the category icons component when the relevant setting is enabled. This avoids the missing category icons component from breaking this component.
This relies on a class name update in the category icons component. https://github.com/discourse/discourse-category-icons/pull/19

UX: category icon compatibility improvements

---

javascripts/discourse/components/discourse-category-banners.js

The `category-header` class was lingering when it shouldn't have been. This ensures it's always removed when the banner doesn't render.

DEV: ensure class removal when banner doesn't show

---

javascripts/discourse/components/discourse-category-banners.hbs
javascripts/discourse/components/discourse-category-banners.js
javascripts/discourse/services/category-banner-presence.js

Pairs with the tag banner component changes here: https://github.com/discourse/discourse-tag-banners/pull/9
This adds a `CategoryBannerPresence` service, which helps with integrating with the tag banner component along with a `category-banners-after-title` plugin outlet.
I've also removed property changes from the getters.

FEATURE: add features for tag banner integration, clean up

---

common/common.scss
javascripts/discourse/connectors/above-main-container/category-header-banner.hbs
javascripts/discourse/connectors/above-site-header/category-header-banner.hbs
javascripts/discourse/connectors/below-site-header/category-header-banner.hbs
javascripts/discourse/connectors/header-list-container-bottom/category-header-banner.hbs
settings.yml

This adds some more plugin outlets so the banners can now be optionally shown here:
or here:

UX: add more plugin outlet options

---

common/common.scss
javascripts/discourse/components/category-banner.hbs
javascripts/discourse/components/category-banner.js
javascripts/discourse/connectors/above-main-container/category-header-banner.hbs
javascripts/discourse/connectors/above-site-header/category-header-banner.hbs
javascripts/discourse/connectors/below-site-header/category-header-banner.hbs
javascripts/discourse/connectors/header-list-container-bottom/category-header-banner.hbs
javascripts/discourse/initializers/discourse-category-banners.js
settings.yml
spec/system/category_banners_spec.rb
spec/system/page_objects/components/category_banner.rb

This commits introduces the follow changes:
1. Use the `renderInOutlet` API over the connectors convention
1. Renames `discourse-category-banners` component to `category-banner`
which is more appropriate cause we are only rendering banner for one
category.
1. Adds system tests

DEV: Various improvements to theme

---

spec/system/category_banners_spec.rb

1. Use `category.url` instead instead of forming URLs by hand. The
subcategory urls were wrong but the tests were passing since we were
asserting for the component not displaying which will still pass when
the page 404s.
1. Use `let!` instead of `fab!` for `upload_theme_component` since `let!` ensures that the theme cache is cleared between tests.

DEV: Fix flaky and incorrect tests

---

javascripts/discourse/components/category-banner.hbs
spec/system/category_banners_spec.rb

We allow HTML in category descriptions in core, so I think we should still support this (assuming the removal was unintentional, but let me know if we should take another approach @tgxworld!)

FIX: allow HTML in category description

---

.gitignore
common/common.scss
javascripts/discourse/components/category-banner.hbs
settings.yml
spec/system/category_banners_spec.rb
spec/system/page_objects/components/category_banner.rb

This adds a setting `show_category_logo` that when enabled, will include the category logo (from the category's settings) in the banner. 
Another new setting `align_text` can make the text left/center/right aligned.

FEATURE: optionally show category logo, change text alignment

---

locales/en.yml
settings.yml

This commit moves the description for the theme's settings into
`locales/en.yml`. This follows our theme's best practice listed in
https://meta.discourse.org/t/add-localizable-strings-to-themes-and-theme-components/109867

DEV: Move settings descriptions into translation file

---

spec/system/category_banners_spec.rb

This commit improves the test coverage for the client side logic
surrounding the `categories` theme setting

DEV: Add tests for `categories` setting

---

common/common.scss

This makes sure that a readable color is used for usernames in Dark and Light mode.

FIX: correct color for usernames in the description.

---

common/common.scss

sticking to how mentions look in posts for this one
before:
after:

UX: fix mention color

---

javascripts/discourse/components/category-banner.hbs

Add `category` argument to plugin outlet to make it more usable for customization, create new outlet `after-description`

DEV: Improve plugin outlets in category-banner component

---

common/common.scss
javascripts/discourse/components/category-banner.hbs
javascripts/discourse/components/category-banner.js
locales/en.yml
spec/system/category_banners_spec.rb
spec/system/page_objects/components/category_banner.rb

Adds support for core changes to category icons and emojis, allowing them to be shown on category banners.
We will soon be deprecating the [Category Icons](https://meta.discourse.org/t/category-icons/104683) theme component since the functionality has been moved into core.
For categories that don't have an icon or emoji (ie. square badge), we just show the category name when the theme has the show icons setting enabled.
Category emojis:
Category icons:
Private category with default square badge (intentionally omitted):

FEATURE: use category icons and emojis from core

---

common/common.scss
javascripts/discourse/components/category-banner.gjs

Requested here: https://meta.discourse.org/t/could-inline-styles-be-generally-set-with-css-variables/368612
This replaces the inline colors with variables that are assigned the colors. The variables are then applied to the `div[class^="category-title-header"]`. This shouldn't result in any changes other than how the colors are set, overrides in themes will still apply.

DEV: replace inline color with a CSS variable
